from pathlib import Path
import json
import geopandas as gpd

from src.layer_alterator_agent.reference_loader import load_reference_table
from src.layer_alterator_agent.vector_writer import write_attributes_to_vector
from src.layer_alterator_agent.rules_generator import generate_mask_rules


def generate_layer_alterator_inputs(
    vector_path: str,
    reference_table_path: str,
    polygon_descriptions: dict,
    output_dir: str = "data/layer_alterator_outputs",
):
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    reference_df = load_reference_table(reference_table_path)

    updated_vector_path = output_dir / "updated_vector.geojson"
    rules_path = output_dir / "rules.json"
    config_path = output_dir / "simulation_config.json"

    write_attributes_to_vector(
        vector_path=vector_path,
        reference_df=reference_df,
        polygon_descriptions=polygon_descriptions,
        output_path=str(updated_vector_path),
    )

    generate_mask_rules(str(rules_path))

    config = {
        "vector_mask": str(updated_vector_path),
        "rules": str(rules_path),
        "rule_type": "C1",
        "strategy": "deterministic_masking",
        "note": "Generated by Layer Alterator AI Interface Agent"
    }

    with open(config_path, "w", encoding="utf-8") as f:
        json.dump(config, f, indent=2)

    gdf = gpd.read_file(updated_vector_path)

    return {
        "updated_vector_path": str(updated_vector_path),
        "rules_path": str(rules_path),
        "config_path": str(config_path),
        "attribute_table": gdf.drop(columns="geometry").to_dict(orient="records"),
    }